export const FETCH_USER = 'FETCH_USER'
export const FETCH_RECIPES = 'FETCH_RECIPES'
export const ADD_RECIPE = 'ADD_RECIPE'
export const DELETE_RECIPE = 'DELETE_RECIPE'
export const UPDATE_RECIPE = 'UPDATE_RECIPE'
export const START_UPDATING = 'START_UPDATING'

export const POST_NEWUSER = 'POST_NEWUSER'
export const POST_EXISTINGUSER = 'POST_EXISTINGUSER'
export const POST_NEWUSER_SUCCESS = 'POST_NEWUSER_SUCCESS'
export const POST_EXISTINGUSER_SUCCESS = 'POST_EXISTINGUSER_SUCCESS'
export const POST_NEWUSER_FAIL = "POST_NEWUSER_FAIL"
export const POST_EXISTINGUSER_FAIL = 'POST_EXISTINGUSER_FAIL'
